"""empty message

Revision ID: 457736f25de3
Revises: 248b4cb57971
Create Date: 2015-01-30 10:28:12.077120

"""

# revision identifiers, used by Alembic.
revision = '457736f25de3'
down_revision = '248b4cb57971'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
